project_id = "tewgloptmijuaychoxnq"

[functions.backup-offsite]
verify_jwt = false

[functions.enviar-convite-reuniao]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.download-frequencia]
verify_jwt = false
